theme: jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
title: Charlie's blog
description: Random musings

twitter_username: charlietwren
github_username:  charlietw
linkedin_username: charlie-wren
